import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.4/firebase-app.js";import{getAuth,GoogleAuthProvider,setPersistence,browserLocalPersistence,signInWithPopup,signInWithRedirect,getRedirectResult,signOut,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/10.12.4/firebase-auth.js";import{getFirestore,doc,getDoc,setDoc,onSnapshot,enableIndexedDbPersistence}from"https://www.gstatic.com/firebasejs/10.12.4/firebase-firestore.js";
export const firebaseConfig={
  apiKey:"AIzaSyB_BmyjN9kheRyczCoW3Arxl0RpHmDNk9w",
  authDomain:"calendario-iglesia-4517e.firebaseapp.com",
  projectId:"calendario-iglesia-4517e",
  storageBucket:"calendario-iglesia-4517e.firebasestorage.app",
  messagingSenderId:"624610811351",
  appId:"1:624610811351:web:6240fae670fa56e16b3f92"
};let app,auth,db,unsub=null;export async function initFirebase(){app=initializeApp(firebaseConfig);auth=getAuth(app);await setPersistence(auth,browserLocalPersistence);db=getFirestore(app);try{await enableIndexedDbPersistence(db)}catch(e){console.warn(e.code)}try{await getRedirectResult(auth)}catch(e){console.warn(e.code)}return{app,auth,db}}export function onAuth(cb){return onAuthStateChanged(auth,cb)}export async function loginGoogle(){const p=new GoogleAuthProvider();p.addScope("email");try{return await signInWithPopup(auth,p)}catch(e){if(["auth/popup-blocked","auth/popup-closed-by-user","auth/cancelled-popup-request"].includes(e.code))return signInWithRedirect(auth,p);throw e}}export async function logoutGoogle(){return signOut(auth)}export async function loadData(uid,defaults){const ref=doc(db,"users",uid),snap=await getDoc(ref);if(!snap.exists()){await setDoc(ref,defaults,{merge:true});return defaults}return merge(defaults,snap.data())}export function subscribeData(uid,cb){if(unsub)unsub();const ref=doc(db,"users",uid);unsub=onSnapshot(ref,s=>{if(s.exists())cb(s.data())});return unsub}export async function saveData(uid,data){return setDoc(doc(db,"users",uid),data,{merge:true})}export function stopDataSubscription(){if(unsub)unsub();unsub=null}function merge(d,i){return{...d,...i,settings:{...d.settings,...(i.settings||{}),schedules:i.settings?.schedules?.length?i.settings.schedules:d.settings.schedules},people:i.people?.length?i.people:d.people,events:i.events||[],guests:i.guests||[],series:i.series?.length?i.series:d.series}}
